# Generated by Django 5.2.8 on 2025-11-18 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecheck',
            name='content_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitecheck',
            name='error_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sitecheck',
            name='error_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitecheck',
            name='keyword_found',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitecheck',
            name='ssl_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ServiceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.sitecheck')),
            ],
        ),
    ]
