# Generated by Django 5.2.8 on 2025-11-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_sitecheck_content_length_sitecheck_error_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=45)),
                ('test_port', models.IntegerField(blank=True, default=0, null=True)),
                ('test_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='UNKNOWN', max_length=10)),
                ('previous_status', models.CharField(default='UNKNOWN', max_length=10)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
