# Generated by Django 5.2.8 on 2025-11-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_internetconnection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internetconnection',
            options={'ordering': ['provider']},
        ),
        migrations.AddField(
            model_name='internetconnection',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internetconnection',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
