# Generated by Django 5.2.8 on 2025-11-20 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_internetconnection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internetconnection',
            options={},
        ),
        migrations.RemoveField(
            model_name='internetconnection',
            name='error_message',
        ),
        migrations.AddField(
            model_name='internetconnection',
            name='last_alert_status',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='internetconnection',
            name='last_checked',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
