# Generated by Django 5.2.8 on 2025-12-18 05:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_alter_internetconnection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('contact', 'Contact'), ('candidature', 'Candidature Spontanée')], max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.DeleteModel(
            name='InternetConnection',
        ),
        migrations.RemoveField(
            model_name='servicenotification',
            name='site',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.AlterModelOptions(
            name='sitecheck',
            options={'ordering': ['-checked_at']},
        ),
        migrations.AlterField(
            model_name='sitecheck',
            name='checked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sitecheck',
            name='error_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitecheck',
            name='keyword_found',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitecheck',
            name='service_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sitecheck',
            name='ssl_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitecheck',
            name='url',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='ServiceNotification',
        ),
    ]
